chore: add deployer gosuto to gas station
BalancerMaxis/multisig-ops pull request #1013
Opened 2024-06-06 10:30 UTC by gosuto-inzasheru

2024-06-06 10:46 UTC, Tritium-VLK requested changes
20 ETH is a lot.  I think normally we do 1 ETH max and 0.2 or 0.25 for deployers. 

Also interesting that minBalanceWei is not prettified.

2024-06-06 11:27 UTC, gosuto-inzasheru commented
:/ sorry that was a copy paste from polygon

2024-06-07 17:21 UTC, Tritium-VLK approved these changes

2024-06-13 07:50 UTC, gosuto-inzasheru commented
https://etherscan.io/tx/0x737a153af054691dfb39453e9e42ee47e415f6565c48c49881dc9ec6d7013d3b

2024-06-13 07:50 UTC, merged