Create BIP-212.json
BalancerMaxis/multisig-ops pull request #109
Opened 2023-03-14 14:48 UTC by solarcurvey

2023-03-15 05:26 UTC, Tritium-VLK requested changes
Rename this PR/file to cover BIP-212 and 213.  I can take care of it later at some point if you're busy.

2023-03-15 05:26 UTC, Tritium-VLK commented on BIPs/BIP-212, 213.json
> +      "contractInputsValues": {
DAO Multisig should then send the BAL grant to the Timeless DAO Multisig at 0x9a8fee232dcf73060af348a1b62cdb0a19852d13

2023-03-15 05:26 UTC, Tritium-VLK commented on BIPs/BIP-212, 213.json
> +      "contractInputsValues": {
Timeless will manage veBAL in the Timeless DAO multisig at 0x9a8fee232dcf73060af348a1b62cdb0a19852d13 and proposes to whitelist the Timeless Governance Multisig to interact with veBAL.

2023-03-15 05:26 UTC, Tritium-VLK commented on BIPs/BIP-212, 213.json
> +        "contractAddress": "0xBA11E7024cbEB1dd2B401C70A83E0d964144686C"
This looks like it is from BIP-213

2023-03-15 05:26 UTC, Tritium-VLK commented on BIPs/BIP-212, 213.json
> +        "contractAddress": "0xBA11E7024cbEB1dd2B401C70A83E0d964144686C"
Yearn’s yBAL locker/voter has now been deployed…

0xBA11E7024cbEB1dd2B401C70A83E0d964144686C

https://forum.balancer.fi/t/bip-213-whitelist-yearns-ybal-voter-contract-for-vebal/4468

2023-03-15 14:09 UTC, Xeonus commented
Editing BIP-ID to XXX because of delays in when this proposal is going to snapshot.

2023-04-16 12:03 UTC, solarcurvey commented
stale

2023-04-16 12:03 UTC, closed without merging