BIP-675-Enable-Several-E-CLPS-Arbitrum
BalancerMaxis/multisig-ops pull request #1229
Opened 2024-08-07 21:13 UTC by Zen-Maxi

Proposal: https://forum.balancer.fi/t/bip-675-enable-several-e-clps-arbitrum/5915

Rate providers all reviewed but reference https://github.com/balancer/code-review/tree/main/rate-providers for each review.

2024-08-08 08:28 UTC, gosuto-inzasheru requested changes
no rate provider reviews for neither `0x177862A0242acD8b5F9cc757a963c1C8883da45E` nor `0x183Ac1bCC538aa9729350f8a9C6357a268e1Bd03`

2024-08-08 09:08 UTC, gosuto-inzasheru commented
deployments from the `ERC4626RateProviderFactory` cannot automatically be deemed safe.

i requested reviews here: https://github.com/balancer/code-review/issues/123

2024-08-08 23:02 UTC, Zen-Maxi commented
Cannot merge, was unknown to me that aFRAX and aGHO were in these pools. Cannot move forward until their rate providers are reviewed per gosuto's comments above.

2024-08-12 12:24 UTC, gosuto-inzasheru approved these changes

2024-08-13 17:36 UTC, merged