BPI XXX : Add Quest to distribute on GHO gauges
BalancerMaxis/multisig-ops pull request #1342
Opened 2024-09-12 14:15 UTC by Kogaroshi

2024-09-12 20:30 UTC, Tritium-VLK requested changes

2024-09-12 20:30 UTC, Tritium-VLK commented on .vscode/settings.json
> +    "editor.defaultFormatter": "vscode.json-language-features",
Can you please remove this change from the PR?

2024-09-13 06:14 UTC, gosuto-inzasheru reviewed
payloads look great, thanks @Kogaroshi!

since this doesnt require the dao multisig, we are fine to do this without a formal bip :)

will you be adding more gauges to this pr or shall i merge and queue up these ones?

2024-09-13 17:54 UTC, Tritium-VLK approved these changes

2024-09-13 17:55 UTC, merged