sgyd permissions
BalancerMaxis/multisig-ops pull request #1386
Opened 2024-09-27 15:25 UTC by JeronimoHoulin

2024-10-03 19:30 UTC, Tritium-VLK requested changes

2024-10-03 19:30 UTC, Tritium-VLK commented on BIPs/2024-W40/sgyd_permissions.json
> +    "chainId": "1",
need createdFromSafeAddress here.

2024-10-07 11:06 UTC, gosuto-inzasheru commented
https://forum.balancer.fi/t/bip-xxx-allocate-250-000-usdt-to-sgyd/6038

2024-10-08 10:19 UTC, gosuto-inzasheru approved these changes
- i did a review of the permissions payload and wrote a summary on the forum: https://forum.balancer.fi/t/bip-xxx-allocate-250-000-usdt-to-sgyd/6038/3?u=gosuto
- the perms payload is so big that the report cannot be commented here; it exceeds the max amount of characters. i therefore pushed the reports to this pr manually

2024-10-08 10:23 UTC, Tritium-VLK approved these changes

2024-10-11 15:20 UTC, merged