[BIP-715] Enable Automatic Aura Relocking
BalancerMaxis/multisig-ops pull request #1420
Opened 2024-10-10 13:49 UTC by Zen-Maxi

Proposal: https://forum.balancer.fi/t/bip-xxx-enable-automatic-aura-relocking/6077

2024-10-10 17:02 UTC, Tritium-VLK requested changes
There is no link to the reviewed code or the review in the BIP.  The contract is deployed by an unknown deployer.

Recommend not proceeding with this payload until we can clearly link the review to exact code deployed on chain. 

I have asked @mkflow27  to confirm what code he reviewed.  I will work to ensure proper verification in https://github.com/BalancerMaxis/bal_addresses/pull/479

2024-10-10 22:53 UTC, gosuto-inzasheru approved these changes

2024-10-11 15:22 UTC, Tritium-VLK commented
Found evidence of internal review in internal slack.  Verified code deployed matched reviewed code.

2024-10-11 15:22 UTC, Tritium-VLK approved these changes

2024-10-11 15:22 UTC, merged