[BIP-XXX]-Delegate-Gyroscope-GGU-to-DAO-Participants
BalancerMaxis/multisig-ops pull request #1545
Opened 2024-12-04 20:09 UTC by Zen-Maxi

Proposal: https://forum.balancer.fi/t/bip-xxx-delegate-gyroscope-ggu-to-dao-participants/6218/2

Gyroscope Vault: https://etherscan.io/address/0xA2321E23B3060e160195E138b62F8498546B0247#writeContract

2024-12-04 20:15 UTC, Zen-Maxi commented
Pending PR for bal_addresses update: https://github.com/BalancerMaxis/bal_addresses/pull/536

2024-12-05 13:44 UTC, Xeonus commented
@Zen-Maxi payload is wrong, need veballer.eth as delegate, not defilytica.eth!

2024-12-05 13:55 UTC, Xeonus requested changes

2024-12-05 13:55 UTC, Xeonus commented on BIPs/2024-W50/[BIP-XXX]-Delegate-Gyroscope-GGU-to-DAO-Participants.json
> +        "_delegate": "0x99AfD53f807766A8B98400B0C785E500c041F32B",
Change to veballer.eth, thanks

2024-12-09 12:48 UTC, Xeonus approved these changes
Has correct signer set now, incl. 0x9f74662aD05840Ba35d111930501c617920dD68e - veballer.eth

2024-12-09 12:51 UTC, merged