Transactions to submit for Signature (LM & Maxi_ops)
BalancerMaxis/multisig-ops pull request #919
Opened 2024-04-25 16:28 UTC by Hyferion

- remove old OZ v1 relayer from gasstation mainnet **(maxi_ops multisig)**
- replace OZ v1 relayer with v2 on gasstation polygon. Top up: 20 MATIC, min balance: 15 MATIC. **(lm multisig)**
- withdraw funds from now unused lz poker (0xdDd5FF0E581f097573B13f247F6BE736f602F839) on mainnet back to LM wallet (0.34 ETH). **(lm multisig)**

2024-04-25 16:58 UTC, Tritium-VLK requested changes

2024-04-25 16:58 UTC, Tritium-VLK commented on MaxiOps/gasStation/2024-04/lm/withdraw_gas_lz_poker_mainnet.json
> +  "transactions": [
We need to send the ETH back to the gas station as well.  Can you include a second tx in the list send to the resulting eth to the gas station such that there is no end balance change in the safe?

Here's an example: https://github.com/BalancerMaxis/multisig-ops/blob/e35ec951a1942bfe835adc0dd473390f458a8dcc/BIPs/2024-W11/BIP-556.json#L14

2024-04-26 06:17 UTC, gosuto-inzasheru approved these changes

2024-04-26 10:04 UTC, Tritium-VLK submitted a review, later dismissed
LGTM and everything is loaded.  @Hyferion you're welcome to merge this now or once everything is executed.  Whatever works better for your workflows.  Pls make sure it is merged soon after execution at the latest though.

2024-04-29 21:55 UTC, Tritium-VLK approved these changes

2024-04-29 21:59 UTC, merged