BIP-605-inankrETH-ankrETH-Gauge
BalancerMaxis/multisig-ops pull request #959
Opened 2024-05-08 21:50 UTC by Zen-Maxi

BIP: https://forum.balancer.fi/t/bip-xxx-enable-gauge-for-inankreth-ankreth-ethereum/5694

Simulation: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/8d389f08-be54-4dc6-a893-75f8162e7cf3

Specification: The Balancer Maxi LM Multisig eth:0xc38c5f97B34E175FFd35407fc91a937300E33860 will interact with the GaugeAdderv4 at 0x5DbAd78818D4c8958EfF2d5b95b28385A22113Cd and call the addGauge function with the following arguments:

gauge(address): 0xCC9723faDed81a9448a9664c39C0Df2e77FDfA2E
gaugeType(string): Ethereum

2024-05-09 12:47 UTC, gosuto-inzasheru requested changes
i cant find this particular rate provider for ankreth in the code review registry: `0x00F8e64a8651E3479A0B20F46b1D462Fe29D6aBc`

2024-05-14 15:39 UTC, Zen-Maxi commented
Hey; please check the pool page in the future since it is know we have multiple legacy rate providers. ankrETH has an approved gauge live with this rate provider https://app.balancer.fi/#/ethereum/pool/0xdfe6e7e18f6cc65fa13c8d8966013d4fda74b6ba000000000000000000000558 and has had several prior. The contract was deployed >470 days ago. 

https://forum.balancer.fi/t/bip-165-enable-ankreth-eth-gauge-on-ethereum/4308
https://forum.balancer.fi/t/bip-296-migrate-gauge-of-ankreth-weth-to-bbaweth-ethereum/4786
https://forum.balancer.fi/t/bip-311-enable-ankreth-wsteth-gauge-on-ethereum/4820

PS it is included in the update PR for the rate provider repo which is pending merge this week. Line 877 in registry.json https://github.com/balancer/code-review/pull/63/files

2024-05-14 15:54 UTC, Tritium-VLK commented
While I hope that in the future we get our list sorted out, and seems like it will be soon.  This is clear enough evidence that this rate provider is trusted/has been reviewed.

2024-05-14 15:54 UTC, Tritium-VLK approved these changes

2024-05-14 15:54 UTC, merged